//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.15 at 03:36:06 PM CET 
//


package com.klistret.cmdb.ivy.pojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.klistret.cmdb.ivy.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.klistret.cmdb.ivy.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IvyModule }
     * 
     */
    public IvyModule createIvyModule() {
        return new IvyModule();
    }

    /**
     * Create an instance of {@link GlobalExclude }
     * 
     */
    public GlobalExclude createGlobalExclude() {
        return new GlobalExclude();
    }

    /**
     * Create an instance of {@link IvyModule.Conflicts }
     * 
     */
    public IvyModule.Conflicts createIvyModuleConflicts() {
        return new IvyModule.Conflicts();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies }
     * 
     */
    public IvyModule.Dependencies createIvyModuleDependencies() {
        return new IvyModule.Dependencies();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Dependency }
     * 
     */
    public IvyModule.Dependencies.Dependency createIvyModuleDependenciesDependency() {
        return new IvyModule.Dependencies.Dependency();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Dependency.Exclude }
     * 
     */
    public IvyModule.Dependencies.Dependency.Exclude createIvyModuleDependenciesDependencyExclude() {
        return new IvyModule.Dependencies.Dependency.Exclude();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Dependency.Include }
     * 
     */
    public IvyModule.Dependencies.Dependency.Include createIvyModuleDependenciesDependencyInclude() {
        return new IvyModule.Dependencies.Dependency.Include();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Dependency.Artifact }
     * 
     */
    public IvyModule.Dependencies.Dependency.Artifact createIvyModuleDependenciesDependencyArtifact() {
        return new IvyModule.Dependencies.Dependency.Artifact();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Dependency.Conf }
     * 
     */
    public IvyModule.Dependencies.Dependency.Conf createIvyModuleDependenciesDependencyConf() {
        return new IvyModule.Dependencies.Dependency.Conf();
    }

    /**
     * Create an instance of {@link IvyModule.Publications }
     * 
     */
    public IvyModule.Publications createIvyModulePublications() {
        return new IvyModule.Publications();
    }

    /**
     * Create an instance of {@link IvyModule.Publications.Artifact }
     * 
     */
    public IvyModule.Publications.Artifact createIvyModulePublicationsArtifact() {
        return new IvyModule.Publications.Artifact();
    }

    /**
     * Create an instance of {@link IvyModule.Configurations }
     * 
     */
    public IvyModule.Configurations createIvyModuleConfigurations() {
        return new IvyModule.Configurations();
    }

    /**
     * Create an instance of {@link IvyModule.Info }
     * 
     */
    public IvyModule.Info createIvyModuleInfo() {
        return new IvyModule.Info();
    }

    /**
     * Create an instance of {@link ConfigurationsConf }
     * 
     */
    public ConfigurationsConf createConfigurationsConf() {
        return new ConfigurationsConf();
    }

    /**
     * Create an instance of {@link GlobalExclude.Conf }
     * 
     */
    public GlobalExclude.Conf createGlobalExcludeConf() {
        return new GlobalExclude.Conf();
    }

    /**
     * Create an instance of {@link IvyModule.Conflicts.Manager }
     * 
     */
    public IvyModule.Conflicts.Manager createIvyModuleConflictsManager() {
        return new IvyModule.Conflicts.Manager();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Override }
     * 
     */
    public IvyModule.Dependencies.Override createIvyModuleDependenciesOverride() {
        return new IvyModule.Dependencies.Override();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Conflict }
     * 
     */
    public IvyModule.Dependencies.Conflict createIvyModuleDependenciesConflict() {
        return new IvyModule.Dependencies.Conflict();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Dependency.Exclude.Conf }
     * 
     */
    public IvyModule.Dependencies.Dependency.Exclude.Conf createIvyModuleDependenciesDependencyExcludeConf() {
        return new IvyModule.Dependencies.Dependency.Exclude.Conf();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Dependency.Include.Conf }
     * 
     */
    public IvyModule.Dependencies.Dependency.Include.Conf createIvyModuleDependenciesDependencyIncludeConf() {
        return new IvyModule.Dependencies.Dependency.Include.Conf();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Dependency.Artifact.Conf }
     * 
     */
    public IvyModule.Dependencies.Dependency.Artifact.Conf createIvyModuleDependenciesDependencyArtifactConf() {
        return new IvyModule.Dependencies.Dependency.Artifact.Conf();
    }

    /**
     * Create an instance of {@link IvyModule.Dependencies.Dependency.Conf.Mapped }
     * 
     */
    public IvyModule.Dependencies.Dependency.Conf.Mapped createIvyModuleDependenciesDependencyConfMapped() {
        return new IvyModule.Dependencies.Dependency.Conf.Mapped();
    }

    /**
     * Create an instance of {@link IvyModule.Publications.Artifact.Conf }
     * 
     */
    public IvyModule.Publications.Artifact.Conf createIvyModulePublicationsArtifactConf() {
        return new IvyModule.Publications.Artifact.Conf();
    }

    /**
     * Create an instance of {@link IvyModule.Configurations.Include }
     * 
     */
    public IvyModule.Configurations.Include createIvyModuleConfigurationsInclude() {
        return new IvyModule.Configurations.Include();
    }

    /**
     * Create an instance of {@link IvyModule.Info.Extends }
     * 
     */
    public IvyModule.Info.Extends createIvyModuleInfoExtends() {
        return new IvyModule.Info.Extends();
    }

    /**
     * Create an instance of {@link IvyModule.Info.License }
     * 
     */
    public IvyModule.Info.License createIvyModuleInfoLicense() {
        return new IvyModule.Info.License();
    }

    /**
     * Create an instance of {@link IvyModule.Info.Ivyauthor }
     * 
     */
    public IvyModule.Info.Ivyauthor createIvyModuleInfoIvyauthor() {
        return new IvyModule.Info.Ivyauthor();
    }

    /**
     * Create an instance of {@link IvyModule.Info.Repository }
     * 
     */
    public IvyModule.Info.Repository createIvyModuleInfoRepository() {
        return new IvyModule.Info.Repository();
    }

    /**
     * Create an instance of {@link IvyModule.Info.Description }
     * 
     */
    public IvyModule.Info.Description createIvyModuleInfoDescription() {
        return new IvyModule.Info.Description();
    }

}
